name: ClassLibrary CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-build:
    uses: SampleProjectDotNet/reusable-workflows/.github/workflows/dotnet-build-test.yml@main
    with:
      project-name: 'ClassLibrary'
      
    secrets:
      SONAR_PROJECT_KEY:  ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_URL:           ${{ secrets.SONAR_URL }}
      SONAR_TOKEN:         ${{ secrets.SONAR_TOKEN }}

  call-publish:
    needs: call-build
    uses: SampleProjectDotNet/reusable-workflows/.github/workflows/dotnet-publish-nuget.yml@main
    with:
      package-pattern: 'ClassLibrary.1.0.0.nupkg'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

