name: ClassLibrary CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-build:
    uses: SampleProjectDotNet/reusable-workflows/.github/workflows/dotnet-build-test.yml@main
    with:
      project-name: 'ClassLibrary'

    secrets: inherit

  call-publish:
    needs: call-build
    uses: SampleProjectDotNet/reusable-workflows/.github/workflows/dotnet-publish-nuget.yml@main
    secrets: inherit

