name: CI/CD Orquestrado

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: CI – Build, Test, Sonar e Publish
    uses: SampleProjectDotNet/reusable-workflows/.github/workflows/dotnet-build-test.yml@main
    with:
      runSonar: true
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # publish-github:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: '7.x'

  #     - name: Login to GitHub Packages
  #       run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  #     - name: Publish to GitHub Packages
  #       run: dotnet nuget push **/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}