name: ClassLibrary CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-build:
    uses: SampleProjectDotNet/reusable-workflows/.github/workflows/dotnet-build-test.yml@main
    with:
      solution-path: 'ClassLibrary/ClassLibrary.sln'
      project-folder: 'ClassLibrary'
      csproj: 'ClassLibrary/ClassLibrary.csproj'
      runs-on: 'windows-latest'
      runSonar: true
    secrets:
      SONAR_PROJECT_KEY:  ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_URL:           ${{ secrets.SONAR_URL }}
      SONAR_TOKEN:         ${{ secrets.SONAR_TOKEN }}

  call-publish:
    runs-on: windows-latest
    needs: call-build
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact .nupkg
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: ./nupkg
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: 'latest'
      - name: Configure NuGet source
        run: |
          nuget sources add -Name "github" -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" -Username "${{ github.actor }}" -Password "${{ secrets.GITHUB_TOKEN }}" -StorePasswordInClearText

      - name: Push package
        run: |
          nuget push ./nupkg/ClassLibrary.1.0.0.nupkg -Source "github" -ApiKey "${{ secrets.NUGET_API_KEY }}" -SkipDuplicate

